### ISSUE TITLE
make is broken: an error in resample_beta_g

### ISSUE THREAD

**Issue by kim22** [tmills/uhhmm#21]
A fresh clone of the repo and running 'make' runs into the following error.

Traceback (most recent call last):
  File "scripts/d1trainer.py", line 74, in <module>
    main(sys.argv[1:])
  File "scripts/d1trainer.py", line 55, in main
    (samples, stats) = ihmm.sample_beam(word_seq, params, lambda x: io.write_output(x, None, config, pos_seq), lambda x: io.checkpoint(x,config), pickle_file)
  File "/home/m/test/uhhmm/scripts/ihmm.py", line 372, in sample_beam
    resample_beta_g(models, sample.gamma)
  File "/home/m/test/uhhmm/scripts/ihmm.py", line 534, in resample_beta_g
    for l in range(0, models.pos.pairCounts[b][g]):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Makefile:4: recipe for target 'all' failed
make: **\* [all] Error 1

**Comment by tmills** [comment]
Trying to replicate this.
