### ISSUE TITLE
Possible memory leak in c++/gpu version

### ISSUE THREAD

**Issue by tmills** [tmills/uhhmm#42]
Exited after about 900 iterations with this exception:

INFO:root:Distributed model compiler done in 170 s with 46078500 non-zero values
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "PyzmqWorker.pyx", line 105, in PyzmqWorker.PyzmqWorker.run (scripts/PyzmqWorker.c:3326)
  File "gpusrc/CHmmSampler.pyx", line 32, in CHmmSampler.GPUModel.__cinit__ (gpusrc/CHmmSampler.cpp:2043)
    self.c_model = new Model(pi_num_rows, pi_num_cols, &pi_data[0], pi_data_size, &pi_indptr[0], pi_indptr_size, &pi_indices[0], pi_indices_size,\
MemoryError: std::bad_alloc: out of memory

**Comment by lifengjin** [comment]
I don't know if it is because I used some implicit destructors for some classes. Anyway, I have made them explicit and put in some dealloc in the CUDA code. hopefully it is not because of some intricate interactions between CUDA and Cython.

**Comment by tmills** [comment]
Don't notice this anymore so I'm going to close it.
